#!/bin/sh

set -e

sudo apt-get -yy -q install zsh curl git

rm -rf ~/.dotfiles ~/.oh-my-zsh

echo 'installing dotfiles'
git clone https://github.com/kian/dotfiles.git ~/.dotfiles
cd ~/.dotfiles
echo 'O' | script/bootstrap

cd ..
echo 'installing oh-my-zsh'
curl -L http://install.ohmyz.sh | zsh
